### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [konveyor/move2kube#1064]
**Describe the bug**
The documentation link inside the Usage section in Readme file is broken. It shows a page not found error upon visiting that link.
https://github.com/konveyor/move2kube/blob/a49a808a8840c32cabe9f31ccbd7ea8cf3c48be6/README.md?plain=1#L66

**To Reproduce**
1. Go to https://github.com/konveyor/move2kube/blob/main/README.md
2. Scroll down to Usage section
3. Click on Documentation 
4. See Page Not Found

**Expected behavior**
Open up Move2Kube Documentation

**Screenshots**
![image](https://github.com/konveyor/move2kube/assets/17739006/654240a3-4946-4fe0-8101-5b36f11f0c1d)

**Desktop (please complete the following information):**
 - OS: [e.g. RHEL]
 - Version [e.g. 22]. `move2kube version` should return it.

**Additional context**

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to fix it

**Comment by seshapad** [comment]
sure @Prakhar-Agarwal-byte . Please raise a PR. We will review it.

**Comment by seshapad** [comment]
@Prakhar-Agarwal-byte Thank you for the contribution. Please note a small point. When issue is created, please use the prefix to indicate if it is doc, feature or fix.

**Comment by Prakhar-Agarwal-byte** [comment]
@seshapad Sure, I will keep that in mind
