### ISSUE TITLE
In Generated Dockerfile COPY Command syntax formed incorrectly 

### ISSUE THREAD

**Issue by move2git** [konveyor/move2kube#1097]
**Describe the bug**
As is generated  : COPY --from= rating-buildstage/app/target/rating-0.0.1-SNAPSHOT.jar .
It has to be like  : COPY --from=rating-buildstage /app/target/rating-0.0.1-SNAPSHOT.jar .

There should be space between image name build jar file path, but instead the space presented after =
COPY --from=<repository_image_name> <path of actual file intended to be copied> <destination location>

**To Reproduce**
1. Using the Mov2Kube UI Version http://localhost:8080/
2. After Planning, use Tranform to the generate the outcome
3. go to the scripts folder in the output directory generated, run the command buildimages.bat podman
    STEP 1/3: FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
    STEP 2/3: COPY rating-0.0.1-SNAPSHOT.jar .
    --> 62de1907ec18
    STEP 3/3: COPY --from= rating-buildstage/app/target/rating-0.0.1-SNAPSHOT.jar .
    Error: COPY --from=: no stage or image found with that name

**Expected behavior**
The build should have completed without any errors

**Screenshots**
    STEP 3/3: COPY --from= rating-buildstage/app/target/rating-0.0.1-SNAPSHOT.jar .
    Error: COPY --from=: no stage or image found with that name

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [e.g. 22]. `version: v0.3.11-rc.0 gitCommit: 82196544d43ab6ae9f93efe9d9f5408b411d6374 gitTreeState: clean

**Additional context**
Rest all works fine, I have even tried it seperately, special thanks to Padmanabha V Seshadri to helping in slack community to go forward

**Comment by HarikrishnanBalagopal** [comment]
@move2git Thanks for raising the issue.

In the Move2Kube UI please go to the Support page and copy/paste the details here.
This will help us debug the issue.

**Comment by move2git** [comment]
@HarikrishnanBalagopal I have pasted the details now

**Comment by HarikrishnanBalagopal** [comment]
Thanks, possibly the space in this line between `--from` and the container name https://github.com/konveyor/move2kube/blob/9bc4e8b017e995ad6cab70f9f9e28a3508ad52d5/assets/built-in/transformers/dockerfilegenerator/java/jar/templates/Dockerfile.jar-run#L7

**Comment by move2git** [comment]
@HarikrishnanBalagopal Thank you so much Hari for quickly looking at it and pointing to it. I also want to start contributing to open source. I don't know how to start and setup a test/debug environment in my local. Is there any help available to look in to it

**Comment by move2git** [comment]
> Thanks, possibly the space in this line between `--from` and the container name
> 
> https://github.com/konveyor/move2kube/blob/9bc4e8b017e995ad6cab70f9f9e28a3508ad52d5/assets/built-in/transformers/dockerfilegenerator/java/jar/templates/Dockerfile.jar-run#L7
> 
> Should make it similar to
> 
> https://github.com/konveyor/move2kube/blob/9bc4e8b017e995ad6cab70f9f9e28a3508ad52d5/assets/built-in/transformers/dockerfilegenerator/java/tomcat/templates/Dockerfile.tomcat#L24
> 
> I think the space got introduced accidentally in this PR https://github.com/konveyor/move2kube/pull/1001/files#diff-04b72caa3d4688f1c2eaa6edaca8db27cee3e2abd814dcff0d169c23b47a5d09R7

Space should be between Container Name and DeploymentFilePath, you rightly pointed out in the fix
Bug: --from= {{ .BuildContainerName }}{{ end }}{{ .DeploymentFilePath }}
Fix: --from={{ .BuildContainerName }} {{ end }}{{ .DeploymentFilePath }}

**Comment by move2git** [comment]
@HarikrishnanBalagopal once done with fix and moved to pre-prod/prod, keep me informed, I will test it and confirm

**Comment by HarikrishnanBalagopal** [comment]
> @HarikrishnanBalagopal Thank you so much Hari for quickly looking at it and pointing to it. I also want to start contributing to open source. I don't know how to start and setup a test/debug environment in my local. Is there any help available to look in to it

Nice! You can take a look at one of our issues labelled `hacktoberfest` for some idea on how to get started https://github.com/konveyor/move2kube/issues/881
