### ISSUE TITLE
bug: DefaultExecutablePermission is not used anywhere

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#1103]
https://github.com/konveyor/move2kube/blob/73077ae4f7e79f9c7f95208963ba284407f627af/common/constants.go#L42

<img width="381" alt="image" src="https://github.com/konveyor/move2kube/assets/20921177/b6abd323-8d22-479c-ac14-b6bf8a7fff17">

## Related

How are executable scripts like `buildimages.sh` produced with the correct permissions?

Seems to be coming from https://github.com/konveyor/move2kube/blob/73077ae4f7e79f9c7f95208963ba284407f627af/assets/filepermissions.yaml#L34

https://github.com/konveyor/move2kube/blob/73077ae4f7e79f9c7f95208963ba284407f627af/main.go#L31-L32

**Comment by Akash-Nayak** [comment]
```How are executable scripts like buildimages.sh produced with the correct permissions?```

@HarikrishnanBalagopal, I think the original permissions of the files (like, buildimages.sh, pushimages.sh, etc.) in the local machine, which is used for pushing these files, gets added/updated in the filepermissions.yaml file when we run `make generate`.

**Comment by Soumil-07** [comment]
I checked the blame output for constants.go, and DefaultExecutablePermission was added in the very 2nd commit 3 years ago: 6b90cbd5453c8eddf894823a62ef8373c043c8c7. Even back then, it wasn't used anywhere.
