### ISSUE TITLE
Set default value for copysources

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#111]
Update copysources.sh with the default value of the source path, so that it works even if no parameters are provided.

This will require changing the copysources.sh template and feeding it with the value of source folder relative to the output folder.

**Comment by PankhudiB** [comment]
> Update copysources.sh with the default value of the source path, so that it works even if no parameters are provided.
> 
> This will require changing the copysources.sh template and feeding it with the value of source folder relative to the output folder.

whatis the default value of source path ?

**Comment by ashokponkumar** [comment]
@seshapad Can you provide guidance to @PankhudiB on how to go about this activity?
