### ISSUE TITLE
bug: version metadata is empty when the tag is non empty?

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#1112]
https://github.com/konveyor/move2kube/blame/e88ceceee7e8e76a587827d9555035566d4d0b38/Makefile#L58

**Comment by akagami-harsh** [comment]
@HarikrishnanBalagopal , can you please give some more information about the issue

**Comment by HarikrishnanBalagopal** [comment]
> @HarikrishnanBalagopal , can you please give some more information about the issue

cc: @ashokponkumar The `VERSION_METADATA` was added a long time ago
```
VERSION_METADATA = unreleased
ifneq ($(GIT_TAG),)
	VERSION_METADATA =
endif
```
not sure if this is really a bug?
Few options instead of leaving it empty:
- `VERSION_METADATA = released`
- `VERSION_METADATA = prerelease` and `VERSION_METADATA = stable` depending on the git tag/version
