### ISSUE TITLE
Add "m2k" as alias for move2kube on installation of move2kube

### ISSUE THREAD

**Issue by KrishAryan** [konveyor/move2kube#1135]
**Is your feature request related to a problem? Please describe.**

It's frustrating to write move2kube all the time.

**Describe the solution you'd like**

Set an alias m2k for move2kube by default on installation

**Comment by kmehant** [comment]
Thanks for raising the issue, I think it should be simple to add something like

```
alias m2k="move2kube"
```
in the user's shell profile,  we probably can leave this to the user how they wish to alias the move2kube command rather defaulting it in the installation process.

cc @HarikrishnanBalagopal @seshapad

**Comment by Sanket-0510** [comment]
> Thanks for raising the issue, I think it should be simple to add something like
> 
> ```
> alias m2k="move2kube"
> ```
> 
> in the user's shell profile, we probably can leave this to the user how they wish to alias the move2kube command rather defaulting it in the installation process.
> 
> cc @HarikrishnanBalagopal @seshapad

Folks often aren't aware regarding such commands, adding it to the readme I guess this thing can be done.
