### ISSUE TITLE
Add uninstallation scripts and docs for move2kube

### ISSUE THREAD

**Issue by KrishAryan** [konveyor/move2kube#1136]
**Is your feature request related to a problem? Please describe.**

Cannot find a clean up guide or docs for move2kube CLI or UI

**Describe the solution you'd like**

Add clean up guide  and docs for move2kube or point CLI and UI

**Comment by HarikrishnanBalagopal** [comment]
```Cannot find uninstallation script or docs for move2kube CLI or UI```
At least for the UI the instructions are for running as a docker container https://github.com/konveyor/move2kube-ui?tab=readme-ov-file#starting-the-ui so there's no uninstall step involved.
