### ISSUE TITLE
Add support for enabling/disabling QA categories to the Move2Kube API 

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#1155]
**Is your feature request related to a problem? Please describe.**
Currently, only Move2Kube CLI can be used for enabling or disabling the QA categories using `--qa-disable` or `--qa-enable` flag while running `move2kube transform`. There is no support for enabling/disabling QA categories in Move2Kube API. 

**Describe the solution you'd like**
Similar to Move2Kube CLI, Move2Kube API should also support enabling/disabling QA categories during the transform phase. Move2Kube API should also allow to enable/disable multiple categories, as can be done with CLI using `--qa-disable` or `--qa-enable` flag multiple times.

**Additional context**
https://github.com/konveyor/move2kube/issues/1151#issuecomment-1993816895

**Comment by HarikrishnanBalagopal** [comment]
Fixed in https://github.com/konveyor/move2kube/pull/1158
