### ISSUE TITLE
bug: running Move2Kube transform on Windows machine throws an error about qamapping file not being present

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#1192]
# Overview

Running the Move2Kube CLI in a Windows 11 machine (inside Cygwin and Powershell) causes a crash.

https://github.com/konveyor/move2kube/blob/c1a0f8a4db1014370e39d15a27a022a019e0e9c6/cmd/utils.go#L89-L125

## Steps to reproduce

1. Run `move2kube transform`

## Actual behavior

Crash saying the qamappings.yaml file doesn't exist.

## Expected behavior

Should print the usage info

## Environment

 - OS: Windows 11
 - Version: https://github.com/konveyor/move2kube/releases/tag/v0.3.14

**Comment by HarikrishnanBalagopal** [comment]
Related https://github.com/konveyor/move2kube/commit/c8164a0733989ac93ef68bb8cc2431cbdc80e115#diff-d23edd34a745e08894f91860da46601946a8f0ae3a970d794c981d4014f30614L57-L61

**Comment by Akash-Nayak** [comment]
The error could be due to this hard coded path `built-in/qa` https://github.com/konveyor/move2kube/blob/c1a0f8a4db1014370e39d15a27a022a019e0e9c6/cmd/utils.go#L116

**Comment by HarikrishnanBalagopal** [comment]
https://github.com/golang/go/issues/45230#issuecomment-806554753
