### ISSUE TITLE
Support custom ports for the backend service of an Ingress path. Support exposing multiple ports under different paths.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#120]
Right now we always set the backend service port of an ingress path to the default port:
https://github.com/konveyor/move2kube/blob/0a6db0083e27350c05c83219fc5820da3ddc2841/internal/apiresource/service.go#L413

Add support for setting a custom port.
Use case: preserving ports while translating docker compose and old k8s projects.

**Comment by ashokponkumar** [comment]
@HarikrishnanBalagopal This issue is fixed in the latest release, isn't it?
