### ISSUE TITLE
Make tekton pipeline resource more generic to support use cases outside CI/CD.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#121]
Currently the pipeline resource is very much tailored for CI/CD pipeline generation:
https://github.com/konveyor/move2kube/blob/0a6db0083e27350c05c83219fc5820da3ddc2841/internal/apiresource/pipeline.go#L62-L154

Make the creation of the pipeline more generic so it can be used for more things.

**Comment by ashokponkumar** [comment]
Using templates in v3 this can be achieved
