### ISSUE TITLE
Pull traversal of source directory up to a higher level and consolidate m2kignore logic. Also reconsider service naming logic.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#122]
Right now each source translator does their own traversal and their own `m2kignore` logic:
https://github.com/konveyor/move2kube/blob/0a6db0083e27350c05c83219fc5820da3ddc2841/internal/source/any2kube.go#L58-L108

Pull the traversal code to a higher level, maybe here:
https://github.com/konveyor/move2kube/blob/0a6db0083e27350c05c83219fc5820da3ddc2841/internal/move2kube/planner.go#L41-L50

This avoids duplicating the `m2kignore` logic and should simplify the logic inside each source translator's `GetServiceOptions`

**Comment by HarikrishnanBalagopal** [comment]
Also consider supporting returning multiple services for a single folder.
Instead of containerizing folders, containerize files and folders?

Use case: Multiple `.war` files in the same folder.

**Comment by HarikrishnanBalagopal** [comment]
# Bug Description

Need to reconsider service naming logic to avoid different services ending up with the same name.

# Steps to Reproduce

1. Have a directory structure like this
```
.
└── lang
    ├── a
    │   └── nodejs
    │       ├── main.js
    │       └── package.json
    ├── b
    │   └── nodejs
    │       ├── main.js
    │       └── package.json
    ├── golang
    │   └── main.go
    └── python
        ├── main.py
        └── requirements.txt
```
2. run `move2kube translate -s lang/`

# Actual behaviour

```
? 1. Select all services that are needed: 
Hints: 
 [The services unselected here will be ignored.]
  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [✓]  python
  [✓]  nodejs
  [✓]  golang
```

```
? 4. Select containerization technique for service nodejs: 
Hints: 
 [Choose the containerization technique of interest.]
  [Use arrows to move, type to filter]
> NewDockerfile
  S2I
  CNB
  NewDockerfile
  S2I
  CNB
```

# Expected behaviour

Expected the 2 nodejs services to have different names and show up as separate services.
Also expected the containerization target options to not have duplicates.

# Additional Context

Related issue https://github.com/konveyor/move2kube/issues/138

**Comment by ashokponkumar** [comment]
Also, be conscious of duplicate services. For example, don't add new services as Dockerfile2kube, if the same dockerfile was used in compose2kube.

For example, https://github.com/konveyor/move2kube-demos/tree/main/samples/docker-compose/multiple-services recognizes web and move2kube-demos-web as two options.
