### ISSUE TITLE
Enhancement: Install Helm 3 if it is not present

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#154]
Right now we are not checking for Helm:
https://github.com/konveyor/move2kube/blob/b68649ed6a2217e9990bcc0b7828fd9c761fdd68/scripts/installdeps.sh#L23-L26

Check if Helm is installed and if not install Helm 3, possibly using https://github.com/helm/helm/blob/master/scripts/get-helm-3

**Comment by ashokponkumar** [comment]
Helm is not a requirement for move2kube. It is required only for using moce2kube artifacts. Hence closing.
