### ISSUE TITLE
Add instructions on how to proceed after `deploy.sh`

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#168]
It's unclear what needs to be done after deploying.

Probable steps that need to be taken after deployment:
1. Copy everything inside `myproject/containers/` into their respective `git` repos
1. Check in all the changed files/folders.
1. Maybe look at changing the generated files to enable additional features like CI/CD, liveliness/readiness probes, etc.

**Comment by ashokponkumar** [comment]
Have a more simplified readme with generic instructions on next steps.
