### ISSUE TITLE
Add a ASCII cinema recording of e2e-flow sample to README, with curl in the end to show output

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#173]

**Comment by ashokponkumar** [comment]
@Akash-Nayak can we do this as part of the website work and update the readme too?

**Comment by Akash-Nayak** [comment]
Yes sure, I will do that.

**Comment by Akash-Nayak** [comment]
@ashokponkumar If PR https://github.com/konveyor/move2kube/pull/179 resolves this issue, then can you please close this issue. Thanks.

**Comment by ashokponkumar** [comment]
Lets create a svg and embed it and close this. the asciinema is ending up redirecting to a page.
