### ISSUE TITLE
Move Konveyor link to have Konveyor logo say at bottom of page.

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#190]
**Is your feature request related to a problem? Please describe.**
Konveyor logo is missing from the website

**Describe the solution you'd like**
Move Konveyor link to have Konveyor logo say at bottom of page.

**Comment by ashokponkumar** [comment]
@Akash-Nayak FYA.

**Comment by Akash-Nayak** [comment]
Added Konveyor logo in the footer- https://github.com/konveyor/move2kube/pull/206
