### ISSUE TITLE
Installation should have 2 subsections for command line tool and web based tool

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#191]
Instead of a single page for Installation, we can have multiple pages like the Tutorial section. Each page talking about command line and web tool separately.

The base installation page should talk about the fact that move2kube can be consumed as either command line or web, and point to them.

**Comment by ashokponkumar** [comment]
@Akash-Nayak FYA

**Comment by Akash-Nayak** [comment]
Added separate pages for installing Move2Kube command line and web tool- https://github.com/konveyor/move2kube/pull/203
