### ISSUE TITLE
Simplify Getting started page and move it below Installation nav section

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#193]
Clean up "Getting Started" page. Probably we can have only those two images on one step approach and 2/3 step approach. And possibly snapshots of the 3 pages of the UI.

We can link it to the tutorials section for more details.

Also move the link to be below "Installation" section.

**Comment by ashokponkumar** [comment]
@Akash-Nayak FYA

**Comment by Akash-Nayak** [comment]
Updated the "Getting Started" page - https://github.com/konveyor/move2kube/pull/202
