### ISSUE TITLE
Look at and use java server artifacts like root.xml

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#215]
**Describe the bug**
When translating java web applications, servers like tomcat serve the generated `.war` file at a particular path.
This path called the context root can be changed using files like `root.xml`

See following for more details:
- https://docs.oracle.com/cd/E39271_01/studio.300/studio_install/src/tidi_studio_tomcat_bundle_linux_context_root.html
- https://tomcat.apache.org/tomcat-8.0-doc/config/context.html

Currently we are not looking for, nor are we using these server artifacts.
This can lead to the application being served on the wrong path.

**To Reproduce**
1. Translate a java web application that has some server artifacts.

**Expected behavior**
move2kube should try to use the server artifacts by placing them in the correct directories in the final container image.

**Comment by ashokponkumar** [comment]
We should cater to these for tomcat, jboss and liberty.

**Comment by ashokponkumar** [comment]
We allow for extensive choices on context path and ability to templatize docker files
