### ISSUE TITLE
Improve Code coverage for unit tests

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#22]
Improve Code coverage for unit tests in the various packages of move2kube.

**Comment by faabiosr** [comment]
I take care to improve the tests.

**Comment by ShajithaMohammed** [comment]
I can help with unit tests for `optimize` package.

**Comment by ashokponkumar** [comment]
sure @ShajithaMohammed . Please reach out to us if you need more specific questions. 

cc @HarikrishnanBalagopal Please let @ShajithaMohammed know if you have any specific tips.

**Comment by HarikrishnanBalagopal** [comment]
@ShajithaMohammed Thanks for the PR. I will leave this issue open because it is about getting 100% (or as close to 100%) line coverage.
