### ISSUE TITLE
Slack, GitHub and Google Groups logos are not getting displayed properly on mobile browser.

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#224]
**Describe the bug**
The Slack, Forum and GitHub icons are not getting displayed properly on mobile browser. The light version of GitHub logo is being used which looks fine on desktop browser but it is completely invisible on the mobile browser.

**To Reproduce**
1. Go to https://konveyor.github.io/ move2kube on a mobile browser.
2. Scroll down till the end of homepage

**Expected behavior**
Display the logos clearly.

**Screenshots**
<img width="453" alt="Screenshot 2020-11-15 at 3 54 28 PM" src="https://user-images.githubusercontent.com/14867323/99183708-d133a380-2763-11eb-8470-8152e727fce0.png">

**Comment by ashokponkumar** [comment]
Also the hover text of these buttons seem to have a / in the end.
