### ISSUE TITLE
Create install script

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#23]
Create install script which will download the latest release and place it in the right folders which are in path.

1. Script that will download the latest release (not from source) from https://github.com/konveyor/move2kube/releases depending on the operating system and install it in the right path. A simpler version of https://github.com/helm/helm/blob/master/scripts/get-helm-3.
2. Also, please place the script in scripts folder and update the USAGE.md and README.md.

Install process should be as simple as `curl https://raw.githubusercontent.com/konveyor/move2kube/master/scripts/install.sh | bash`

**Comment by Ocramoi** [comment]
I can take care of it! Can you assign me to the issue?

**Comment by Ocramoi** [comment]
I sent a PR with the install script, if you wanna take a look

**Comment by ashokponkumar** [comment]
> I sent a PR with the install script, if you wanna take a look

Thanks @Ocramoi . Have added some comments to the PR. Please take a look. Will be happy to review the PR again.
