### ISSUE TITLE
Add a S2I working sample

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#234]
**Is your feature request related to a problem? Please describe.**
Add a S2I working sample

**Describe the solution you'd like**
Add a S2I working sample

**Describe alternatives you've considered**
Manually try.

**Comment by ashokponkumar** [comment]
@Akash-Nayak Can you please try converting the language platforms with s2i and check if we have any issues.

**Comment by Akash-Nayak** [comment]
Yes Sure.

**Comment by Akash-Nayak** [comment]
While running `move2kube-demos git:(main) $ move2kube translate -s samples/language-platforms`, in the first QA it asked me to select the services and there was one service named move2kube-demos.
```
? 1. Select all services that are needed: 
Hints: 
 [The services unselected here will be ignored.]
  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [✓]  java-gradle
  [✓]  java-maven-war
  [✓]  python
  [✓]  move2kube-demos
  [✓]  golang
  [✓]  nodejs
  [✓]  php

golang, java-maven-war, nodejs, php, python, ruby, move2kube-demos, java-gradle-war, java-maven, java-gradle
```
java-maven and java-gradle-war which were not in the options also appeared in the selected services.

I got few warning messages after I selected S2I as the containerization technique.
```
? 2. Select all containerization modes that is of interest: 
Hints: 
 [The services which does not support any of the containerization technique you are interested will be ignored.]
 S2I
WARN[0039] Ignoring service java-gradle-war, since it does not support any selected containerization technique. 
WARN[0039] Ignoring service java-gradle, since it does not support any selected containerization technique. 
WARN[0039] Ignoring service java-maven-war, since it does not support any selected containerization technique. 
WARN[0039] Ignoring service move2kube-demos, since it does not support any selected containerization technique. 
? 3. Choose the artifact type: 
```

After the translation was complete, I deployed the artifacts to the Kubernetes cluster and the below mentioned services are running successfully.

```
The services are accessible on the following paths:
golang : http://myproject.irlhc12-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud/golang
java-maven : http://myproject.irlhc12-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud/java-maven
nodejs : http://myproject.irlhc12-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud/nodejs
php : http://myproject.irlhc12-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud/php
python : http://myproject.irlhc12-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud/python
ruby : http://myproject.irlhc12-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud/ruby
```
<img width="1093" alt="Screenshot 2020-11-18 at 12 21 50 PM" src="https://user-images.githubusercontent.com/14867323/99495420-a54d3380-2998-11eb-8b7f-e8d1211cb777.png">
<img width="1091" alt="Screenshot 2020-11-18 at 12 22 17 PM" src="https://user-images.githubusercontent.com/14867323/99495464-b6964000-2998-11eb-8442-2d01980cd1d7.png">
<img width="1093" alt="Screenshot 2020-11-18 at 12 22 55 PM" src="https://user-images.githubusercontent.com/14867323/99495529-ce6dc400-2998-11eb-882e-8def7e748554.png">
<img width="1086" alt="Screenshot 2020-11-18 at 12 23 28 PM" src="https://user-images.githubusercontent.com/14867323/99495577-dfb6d080-2998-11eb-8628-c339f9efce63.png">
<img width="1094" alt="Screenshot 2020-11-18 at 12 24 13 PM" src="https://user-images.githubusercontent.com/14867323/99495674-f9f0ae80-2998-11eb-8775-d6faa7eb115d.png">
<img width="1095" alt="Screenshot 2020-11-18 at 12 24 55 PM" src="https://user-images.githubusercontent.com/14867323/99495730-12f95f80-2999-11eb-86de-6da510ec6ade.png">

**Comment by Akash-Nayak** [comment]
Added S2I working example using the language-platforms sample usecase - https://github.com/konveyor/move2kube/pull/240
