### ISSUE TITLE
When build context is provided in docker compose, reusedockerfilecontainerizer is not performing correctly

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#239]
**Describe the bug**
When build context is provided in docker compose, reusedockerfilecontainerizer is not performing correctly

**To Reproduce**
When build context is provided in docker compose, reusedockerfilecontainerizer is not performing correctly

**Expected behavior**
When build context is provided in docker compose, reusedockerfilecontainerizer should be able to find the dockerfile and create build scripts

**Comment by ashokponkumar** [comment]
Wasn't this fixed in one of the previous PRs?

**Comment by ashokponkumar** [comment]
@HarikrishnanBalagopal We can close this issue if this is fixed.

**Comment by HarikrishnanBalagopal** [comment]
yeah this was fixed by https://github.com/konveyor/move2kube/pull/238
