### ISSUE TITLE
ConfigMap/Secrets/PVCs should be created based on the characteristics of data

### ISSUE THREAD

**Issue by seshapad** [konveyor/move2kube#242]
Characteristics of data such as:
1.  Size of the data 
2. Whether data is encrypted or not 
3. Data is a binary file or a text file or key/value pair

Above characteristics and more could be used to determine which type of storage modality is most appropriate. For instance, small data sizes or text of key/value pairs are more suitable as ConfigMaps, while encrypted content could be good as secrets, and large binary data could be a PVC.

**Comment by seshapad** [comment]
This link has some use case for above issue: https://stackoverflow.com/questions/62545373/how-to-convert-docker-compose-yaml-file-to-kubernetes-yaml-file-for-deployment

**Comment by ashokponkumar** [comment]
Each org might have different requirements. Better to achieve it using customization.
