### ISSUE TITLE
Add inbuilt support for popular managed cloud kubernetes services

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#25]
The task involves the following:

1. Setting up a terminal with the cluster in context for kubectl
1. Run `move2kube collect`
1. Copy the m2k_collect/clusters/<file>
1. Change name to <clustername>.yaml
1. In yaml, change metadata.name to clustername used above
1. Check in to https://github.com/konveyor/move2kube/tree/master/internal/metadata/clusters
1. Do `make generate`
1. Submit a pull request after committing with `git commit -s -m comment`

**Comment by ashokponkumar** [comment]
@akhil-ghatiki If you have access to any kubernetes cluster from any of the cloud services, this might be a easy issue to fix, in case you are interested.

**Comment by akhil-ghatiki** [comment]
I will check this out. I think I better work on this first than Add collector for Amazon ECS and Azure Container Service #43. (Because #43 requires lot of other exploration)

**Comment by akhil-ghatiki** [comment]
@ashokponkumar I have set up the terminal with the cluster in context for kubectl for an aws eks. After running the `move2kube collect` the cluster folder is just empty. No yml got generated. 
<img width="1035" alt="Screenshot 2020-10-14 at 10 16 36 PM" src="https://user-images.githubusercontent.com/3032101/96020112-2e89bb80-0e6b-11eb-8a6d-0fecd936bb8e.png">

Is there any other configuration that has to be changed ? OR I afraid if #43 has to be fixed before this can be fixed.

**Comment by ashokponkumar** [comment]
> @ashokponkumar I have set up the terminal with the cluster in context for kubectl for an aws eks. After running the `move2kube collect` the cluster folder is just empty. No yml got generated.
> <img alt="Screenshot 2020-10-14 at 10 16 36 PM" width="1035" src="https://user-images.githubusercontent.com/3032101/96020112-2e89bb80-0e6b-11eb-8a6d-0fecd936bb8e.png">
> 
> Is there any other configuration that has to be changed ? OR I afraid if #43 has to be fixed before this can be fixed.

@akhil-ghatiki #43 is about container service, and is not related to this issue. Can you please share the log output of `move2kube collect -v`?

**Comment by akhil-ghatiki** [comment]
@ashokponkumar any more managed services support is required ? or is this issue good to close ?

**Comment by ashokponkumar** [comment]
If you have access to managed openshift in any of them, we can use them too. If not, lets close it for now.

**Comment by akhil-ghatiki** [comment]
> If you have access to managed openshift in any of them, we can use them too. If not, lets close it for now.

I don't have the access to managed to openshift in them. I think now we can create an issue asking for specific inbuilt support.
