### ISSUE TITLE
Add support for more default dockerfile containerizers

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#26]
Adding a new docker file based containerization technique for move2kube involves the following:

1. Check out other existing dockerfile containerizers in https://github.com/konveyor/move2kube/tree/master/internal/assets/dockerfiles
1. Write a detect script called m2kdfdetect.sh in a new folder similar to https://github.com/konveyor/move2kube/blob/master/internal/assets/dockerfiles/python/m2kdfdetect.sh
1. The detect script should return any parameters that will be required by the dockerfile as a json
1. Write a dockerfile (similar to https://github.com/konveyor/move2kube/blob/master/internal/assets/dockerfiles/python/Dockerfile) which uses the paramters passed above.
1. Do a `make generate`
1. Do a `make build`
1. Test whether `move2kube translate -s srcfolder`, where srcfolder is the folder where a folder containing the application that can be containerized using the above code is present. Check whether move2kube detects it.
1. Check into https://github.com/konveyor/move2kube/blob/master/internal/assets/dockerfiles/
1. Create a pull request.

**Comment by akhil-ghatiki** [comment]
@ashokponkumar wrt point 2 what does "new folder" mean ? 
Does it mean folder other than python ? 
or 
adding totally new folders upon existing folders in /assets/dockerfiles ?

**Comment by ashokponkumar** [comment]
> @ashokponkumar wrt point 2 what does "new folder" mean ?
> Does it mean folder other than python ?
> or
> adding totally new folders upon existing folders in /assets/dockerfiles ?

Totally new folders in /assets/dockerfiles depending on the language you are adding support for.

**Comment by ashokponkumar** [comment]
@seshapad Can you please take the steps in the description, and elaborate on them and create a step by step process of how to create, test and merge a new containerization for Dockerfile and S2I techniques? Once you have it create a folder named "docs" and place the file inside it and create a PR to the repository.

**Comment by akhil-ghatiki** [comment]
@ashokponkumar I am working on this.

**Comment by ashokponkumar** [comment]
> @ashokponkumar I am working on this.

Sure @akhil-ghatiki . Do reach out to @seshapad in this thread if you have any questions.

**Comment by akhil-ghatiki** [comment]
@ashokponkumar Just to reconfirm, I need not commit the generated files from `make generate` for the PR right ? 

Below are the generated files. 
```
internal/assets/constants.go
internal/containerizer/scripts/constants.go
internal/metadata/clusters/constants.go
internal/source/data/constants.go
internal/transformer/templates/constants.go
```

**Comment by ashokponkumar** [comment]
> @ashokponkumar Just to reconfirm, I need not commit the generated files from `make generate` for the PR right ? 
> 
> Below are the generated files. 
> ```
> internal/assets/constants.go
> internal/containerizer/scripts/constants.go
> internal/metadata/clusters/constants.go
> internal/source/data/constants.go
> internal/transformer/templates/constants.go
> ```

You will have to commit them for the builds to pick up
