### ISSUE TITLE
Test the QA cache loader.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#29]
# Description
The `move2kube` tool when run asks the user some questions about how to translate the project.
The answers gathered from this Question Answer (QA) session are stored in a yaml file that we call the QA cache.
The global variable `qaengine` is used to prompt the user and fetch answers during the QA session.

This package looks in the source folder for the QA cache yaml files and loads the filepaths into the plan.
It parses the yaml files it finds to check if they are qa cache files or not before adding them.
During the translate phase it also loads those caches into the QA engine.

# How to get started
❗ Please read the contribution guidelines first https://github.com/konveyor/move2kube/blob/master/contributing.md

To gather some QA caches files to use as testdata, you can run `move2kube` on any of the projects in the samples folder.
You will find a file called `m2kqacache.yaml` in the output directory.

For this issue you should start with some simple tests that creates temporary directories and calls the functions on it.
Next step would be to make slight changes to the files in the directory and create a separate subtest for each scenario.
Some scenarios that are good to test:
- Function called on non existent directory.
- Function called on a file.
- Empty directory.
- Directory we don't have permission to read.
- Directory with only non yaml files.
- Directory with some yaml files that aren't QA cache files.
- Directory with some QA cache files and other random files.

# How to add unit tests
Some guidelines:
- Look at the other tests in the package/project and write similar tests.
- Use subtests to test different paths through the function.
- Don't worry about testing every single path through the function. Focus on common use cases and failure modes.

Some helpful resources on how to write unit tests in Go:
- https://blog.golang.org/subtests
- https://youtu.be/hVFEV-ieeew

# Code to be tested
https://github.com/konveyor/move2kube/blob/731b16a14cd33dd864e51eac3f7945f35266b18f/internal/metadata/qacaches.go#L34-L57

**Comment by ashokponkumar** [comment]
@Akash-Nayak Can you please take a look at this issue? Reach out to @HarikrishnanBalagopal if you have any questions.

**Comment by Akash-Nayak** [comment]
@ashokponkumar Yes sure, I will look at this issue.
