### ISSUE TITLE
Support building using S2I in BuildConfig if Dockerfile is not found

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#307]
# Description
Right now we only support Docker build strategy:
https://github.com/konveyor/move2kube/blob/d2b0fc1ee2f02fd6788ed3f122dadffb23c62097/internal/apiresource/buildconfig.go#L125-L139

# Proposal
Add support for S2I build if Dockerfile is not found.
https://docs.openshift.com/container-platform/4.5/builds/build-strategies.html#build-strategy-s2i_build-strategies

**Comment by ashokponkumar** [comment]
s2i usage varies between orgs, it is easier to use customization to achieve the same.
