### ISSUE TITLE
Support ImageStream in Deployment

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#308]
# Description
DeploymentConfig is not recommended by Openshift/Red Hat. It is meant to be used only in certain situations.
DeploymentConfig might also be deprecated at some point.

# Proposal
Add support for using ImageStreams in Deployments:
https://developers.redhat.com/blog/2019/09/20/using-red-hat-openshift-image-streams-with-kubernetes-deployments/
Just need to add some annotations.

This also allows BuildConfig to work with Deployment.

**Comment by ashokponkumar** [comment]
If there is customer requirements for this feature, we can consider it. For now, it can be achieved using customizations.
