### ISSUE TITLE
Generate a deploy-cicd.sh script when using Tekton for CICD. The script should output the webhook URLs.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#309]
# Description
Generate the `deploy-cicd.sh` script when Tekton is chosen for CICD. Similar to:
https://github.com/konveyor/move2kube/blob/d2b0fc1ee2f02fd6788ed3f122dadffb23c62097/internal/apiresourceset/cicdapiresourceset.go#L154-L166

The script should output the webhook URLs (same as BuildConfig).

**Comment by ashokponkumar** [comment]
no deploy scripts in v3
