### ISSUE TITLE
Don't ignore error and more idiomatic code.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#31]
# Description
1. As mentioned in the TODO https://github.com/konveyor/move2kube/blob/master/internal/metadata/k8sfiles_test.go#L77
we should not continue when the directory has incorrect permissions and we can't read it.

2. The functions we are testing https://github.com/konveyor/move2kube/blob/master/internal/metadata/k8sfiles.go#L36-L80 may not be the most idiomatic way to write them. For example: we have a `continue` and an `else` block.

# Changes to be made
Return with the error in the if block.
https://github.com/konveyor/move2kube/blob/584a35dcd4a23a809edaf0e9cd70080c08bad364/internal/metadata/k8sfiles.go#L39-L42

Change the test to expect the error.

Change the functions to be more idiomatic go.

**Comment by ashokponkumar** [comment]
@vovapi In case you want to take over this issue. Please feel free.
