### ISSUE TITLE
Porting external applications using Move2Kube

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#334]
These are some open-source projects which have `Move to Kubernetes` in their issues.

1. https://github.com/rucken/core-nestjs 
2. https://github.com/rucken/todo-nestjs
3. https://github.com/rucken/core/
4. https://cloud.ibm.com/developer/appservice/starter-kits
5. https://github.com/Tanzu-Solutions-Engineering/pivotal-bank-demo

Will keep adding to the above list when I find more such projects.

**Comment by HarikrishnanBalagopal** [comment]
Not sure if this is relevant anymore.
