### ISSUE TITLE
Create a new QA problem type to allow users to input arrays

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#405]
**Is your feature request related to a problem? Please describe.**
Motivation:
1. We want to allow users to deselect ports we have detected for each service.
2. We want to allow users to add new ports that we didn't detect.
3. We want to allow users to set default ports for all the services and avoid a question per service.

**Describe the solution you'd like**
Add a new problem type `InputArrayProblem` that allows user to input an array.

**Describe alternatives you've considered**
1. Can also modify the multiline type problem (that we aren't really using anywhere) to do this.
2. Can also consider modifying multiselect to be more complicated and use multiple stages to do the same thing.

**Additional context**
Useful when there are a large number of services as seen in some example we tried during demos.

**Comment by ashokponkumar** [comment]
Multiselect with other achieves the goal
