### ISSUE TITLE
Add a question in portmergeoptimizer to allow users to set a default set of ports for all services.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#406]
**Is your feature request related to a problem? Please describe.**
Right now we have hardcoded `8080` as the default service port.
We want the users to be able to change this and specify a list of ports they want as the default.

**Describe the solution you'd like**
Add a `InputArray` type question in portmergeoptimizer with the key `move2kube.services.*.ports`
This will prevent a question being asked per service.

**Additional context**
Requires https://github.com/konveyor/move2kube/issues/405 to be implemented first.

**Comment by ashokponkumar** [comment]
Each transformer supports its own ports, and it can be configured externally using * config option.
