### ISSUE TITLE
Better error messages in unit tests.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#41]
# Description
There are several unit tests that use `reflect.DeepEqual` for comparing the expected output with the actual output of the function. Currently the error messages when the equality check fails is not very helpful.

Example:
https://github.com/konveyor/move2kube/blob/6b90cbd5453c8eddf894823a62ef8373c043c8c7/internal/source/any2kube_test.go#L51-L53

The error message simply prints the expected and actual outputs to the console with no indication of what is different between the two.

This is especially painful for large structs. The difference could be in a single field but finding that field can take ages.

# Fix
Use the cmp package and https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff to print more "human friendly" error messages.

Example:
https://github.com/HarikrishnanBalagopal/move2kube/blob/tekton2/internal/source/any2kube_test.go#L415-L417
Ignore the `cmpopts.EquateEmpty()` part, that is specific to that unit test.

# How to get started
For this issue you should look into as many of the `*_test.go` files as possible and change the error messages.
Good places to start:
- https://github.com/konveyor/move2kube/blob/master/internal/source/any2kube_test.go
- https://github.com/konveyor/move2kube/blob/master/internal/containerizer/dockerfilecontainerizer_test.go
- https://github.com/konveyor/move2kube/blob/master/internal/containerizer/manualcontainerizer_test.go
- https://github.com/konveyor/move2kube/blob/master/internal/containerizer/reusecontainerizer_test.go
- https://github.com/konveyor/move2kube/blob/master/internal/containerizer/s2icontainerizer_test.go
- https://github.com/konveyor/move2kube/blob/master/internal/move2kube/planner_test.go

**Comment by SergeyHydra** [comment]
@HarikrishnanBalagopal I'd like to take this on. Can you assign this issue to me? Thanks.

**Comment by suramrit** [comment]
@HarikrishnanBalagopal Would like to get working on this! Please do add me as an assignee as well :) 
Thanks for the great head start on the issue! 🚀

**Comment by SergeyHydra** [comment]
Cool! I start working on it.

**Comment by SergeyHydra** [comment]
I made pr.
 https://github.com/konveyor/move2kube/pull/45
