### ISSUE TITLE
Consider using https://github.com/markbates/pkger instead of tar if appropriate

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#419]
**Is your feature request related to a problem? Please describe.**
We currently package text files into binary as tar string

**Describe the solution you'd like**
https://github.com/markbates/pkger might give a better interface

**Describe alternatives you've considered**
Using tar string

**Comment by HarikrishnanBalagopal** [comment]
Might be better to use golang's embed feature https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/
instead of relying on a third party library.
