### ISSUE TITLE
Generate cli endpoint for completion on the lines of helm

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#44]
What needs to be done:
1. Checkout the completion scripts in https://github.com/helm/helm/blob/master/cmd/helm/completion.go
1. Model move2kube to have similar commands for generating completion scripts

**Comment by AnaDenisa** [comment]
Hello :) I would like to work on this issue

**Comment by ashokponkumar** [comment]
@AnaDenisa Any updates on this?

**Comment by HarikrishnanBalagopal** [comment]
Shouldn't we use this?
https://github.com/spf13/cobra/blob/master/shell_completions.md

**Comment by ashokponkumar** [comment]
> Shouldn't we use this?
> https://github.com/spf13/cobra/blob/master/shell_completions.md

Yep, we can use that.

**Comment by ashokponkumar** [comment]
Cobra seems to provide by default. So the capability is inbuilt.
