### ISSUE TITLE
Have a way to disable downloading the CNB and Buildpacks images while running move2kube plan

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#445]
**Is your feature request related to a problem? Please describe.**
Running `move2kube plan` for the first time after installing Move2Kube takes 6-8minutes to continue the planning because it downloads the `cloudfoundry/cnb:cflinuxfs3` and the `gcr.io/buildpacks/builder` in the background.

**Describe the solution you'd like**
Have a way to disable downloading the CNB and Buildpacks images while running move2kube plan.

**Comment by ashokponkumar** [comment]
Using config files in plan phase, the new architecture (#464 ) supports selecting transformers.
