### ISSUE TITLE
Change default pull secret name

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#452]
Change default pull secret name to all-icr-io

**Comment by HarikrishnanBalagopal** [comment]
Are we talking about this? https://github.com/konveyor/move2kube/blob/main/internal/customizer/registrycustomizer.go#L139

**Comment by HarikrishnanBalagopal** [comment]
For quay there is no default secret name. You can use whatever name you like:
https://docs.openshift.com/container-platform/4.5/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-from-secure-registries_using-image-pull-secrets
