### ISSUE TITLE
Document usage of Move2Kube in non-interactive mode

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#457]
Document usage of Move2Kube in non-interactive mode, --setconfig and --config.

**Comment by ashokponkumar** [comment]
We should add a comment during execution of move2kube, that the config can be used to run the same flow again without interaction.

**Comment by HarikrishnanBalagopal** [comment]
> We should add a comment during execution of move2kube, that the config can be used to run the same flow again without interaction.

In the output of `move2kube transform`? or in the tutorial?

**Comment by ashokponkumar** [comment]
> > We should add a comment during execution of move2kube, that the config can be used to run the same flow again without interaction.
> 
> In the output of `move2kube transform`? or in the tutorial?

Good question. For now let's add a separate top level tutorial explaining how to run in non interactive mode. If people keep asking the question again, we can add a comment in the execution
