### ISSUE TITLE
Allow specifying transformations in json/yaml patch syntax

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#462]
**Is your feature request related to a problem? Please describe.**
In addition to specifying transformations in starlark `.star` files,
allow `.patch` or something similar with json/yaml patch syntax (similar to kustomize).

**Describe the solution you'd like**
The user will specify the files to apply using a flag. Could be same flag used for `.star` files.

**Describe alternatives you've considered**
NA

**Additional context**
Since we have json/yaml patch syntax for kustomize anyway, it makes sense to use it for some simple transformations.

**Comment by HarikrishnanBalagopal** [comment]
See https://tools.ietf.org/html/rfc6902 and https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md

**Comment by ashokponkumar** [comment]
Lets consider using full kustomize if possible.

**Comment by ashokponkumar** [comment]
With the new external transformer framework that supports starlark, the changes can be autocomputed, which is more efficient since it can support any file type.
