### ISSUE TITLE
If possible return information about resource requirements as well in the new containerizer framework 

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#463]
**Is your feature request related to a problem? Please describe.**
Since the containerizer can return some information about the app in json format,
we can also return information about resource requirements (max or min memory and cpu).

**Additional context**
In some apps the developers have explicitly specified the resource requirements:
https://alvinalexander.com/blog/post/java/java-xmx-xms-memory-heap-size-control/
```
java -Xmx64m -classpath ".:${THE_CLASSPATH}" ${PROGRAM_NAME}
```

**Comment by ashokponkumar** [comment]
With the new framework any information required can be returned by the Transformers and can be used as long as the IR/apireaource or the template supports it. So this will be handled when a source exposes this data.
