### ISSUE TITLE
add feedback on user actions when uploading artifact to m2k UI

### ISSUE THREAD

**Issue by pabloloyola** [konveyor/move2kube#465]
**Is your feature request related to a problem? Please describe.**
When I upload an artifact to move2kube UI, I dont receive any notification on the status of the upload. This can cause some confusion, specially for first time users. 

**Describe the solution you'd like**
Usually, when we upload a file,  systems provide a loading indicator (an animation) and once the file has been uploaded, there is a notification saying `file uploaded successfully`.

**Describe alternatives you've considered**
None

**Additional context**
This is a minor feature, but it could improve the overall user experience when onboarding an app

**Comment by ashokponkumar** [comment]
@pabloloyola Can you please check the current flow, and see if it is fixed?
