### ISSUE TITLE
The transformation scripts are not applied to the helm and kustomize artifacts that we generate

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#477]
**Describe the bug**
The transformations should be applied to all the resources we generate.
Currently only the unparameterized objects are transformed:
https://github.com/konveyor/move2kube/blob/main/internal/transformer/k8stransformer.go#L82

**To Reproduce**
Do a translate on move2kube-demos/samples/language-platforms while providing some starlark transforms using `-t`

**Expected behavior**
All the artifacts should be transformed, including helm and kustomize artifacts.

**Desktop (please complete the following information):**
All

**Additional context**
Need to move the parameterizers to the end.
They should operate after version conversion similar to the fixers.

**Comment by ashokponkumar** [comment]
Will be fixed by #489
