### ISSUE TITLE
Make the IR and other info move2kue collects available in the transformation scripts

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#479]
**Is your feature request related to a problem? Please describe.**
Make all the information that move2kube collects and the IR within the transformation scripts.

**Describe the solution you'd like**
Perhaps something like `ir('k1.k2.k3')`

**Describe alternatives you've considered**
Or maybe something lke `ir['k1']['k2']['k3']`

**Additional context**
Perhaps to get app name or service name?

**Comment by HarikrishnanBalagopal** [comment]
Config is also not available currently.

**Comment by ashokponkumar** [comment]
Centralized IR is no longer there in three new framework
