### ISSUE TITLE
Bug where object is appended even when error occurs.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#48]
# Description
## Bug
https://github.com/konveyor/move2kube/blob/master/internal/apiresource/networkpolicy.go#L56-L60
The object gets appended even when there is an error.

Fix: Add a continue inside the if block.

## Too many checks and error messages
https://github.com/konveyor/move2kube/blob/master/internal/apiresource/networkpolicy.go#L53-L64
The variables `supportedKinds` and `networkPolicyKind` do not change inside the loop. However it keeps checking
if the string `networkPolicyKind` is present in the array `supportedKinds` over and over.
Every time the check fails it prints an error message resulting in lots of error messages about the same thing.

Fix: Move the check and error outside the loop.

## Add unit tests.
Add unit tests for all these functions:
https://github.com/konveyor/move2kube/blob/master/internal/apiresource/networkpolicy.go#L43-L113

# How to get started
❗ Please read the contribution guidelines first https://github.com/konveyor/move2kube/blob/master/contributing.md

First fix the bugs mentioned above, then write the unit tests for the fixed functions.
Since the functions really only have 1 or 2 paths through them the unit tests can also be very simple.

# How to add unit tests
Some guidelines:
- Look at the other tests in the package/project and write similar tests.
- Use subtests to test different paths through the function.
- Don't worry about testing every single path through the function. Focus on common use cases and failure modes.

Some helpful resources on how to write unit tests in Go:
- https://blog.golang.org/subtests
- https://youtu.be/hVFEV-ieeew

# Code to be tested
https://github.com/konveyor/move2kube/blob/731b16a14cd33dd864e51eac3f7945f35266b18f/internal/metadata/k8sfiles.go#L36-L80

**Comment by akashgupta05** [comment]
I'd like to pick up this issue.

**Comment by ashokponkumar** [comment]
Thanks @akashgupta05 . Do reach out if you have any questions.

**Comment by HarikrishnanBalagopal** [comment]
@akashgupta05 if you have done some work on this issue feel free to submit a PR.
Otherwise I would like to takeover.
