### ISSUE TITLE
Add CI/CD artifacts to Helm and Kustomize

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#481]
**Is your feature request related to a problem? Please describe.**
Currently the CI/CD artifacts are simple K8s yamls.
Allow the CI/CD artifacts to be parameterized and deployed using Helm or Kustomize.

**Describe the solution you'd like**
We will need to change the output folder structure to one of the following 2 options:
```
deploy/
  yamls/
    myproject/
    myproject-cicd/
  helm/
    myproject/
    myproject-cicd/
  kustomize/
    myproject/
      base/
      overlays/
        dev/
        staging/
        prod/
    myproject-cicd/
      base/
      overlays/
        dev/
        staging/
        prod/
```

or alternatively we can move the CI/CD folder to the top level

```
deploy/
  yamls/
  helm/
    myproject/
  kustomize/
    base/
    overlays/
      dev/
      staging/
      prod/
cicd/
  yamls/
  helm/
    myproject-cicd/
  kustomize/
    base/
    overlays/
      dev/
      staging/
      prod/
```

**Comment by ashokponkumar** [comment]
Will be fixed by #489
