### ISSUE TITLE
Wrong runtime selected when pom file has Liberty/OpenLiberty elements

### ISSUE THREAD

**Issue by bpaskin-ibm** [konveyor/move2kube#504]
**Describe the bug**
When running `move2kube` against a directory that contains a Maven `pom.xml `and the `pom.xml` contains elements for OpenLiberty/Liberty the tool creates a `Dockerfile`  that includes JBoss, not Liberty.

**To Reproduce**
1. create a pom.xml file with Liberty/OL plugin
```
    <parent>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-app-parent</artifactId>
        <version>3.2.1</version>
    </parent>
```

```
            <plugin>
                <groupId>io.openliberty.tools</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <assemblyArtifact>
                        <groupId>io.openliberty</groupId>
                        <artifactId>openliberty-runtime</artifactId>
                        <version>[18.0.0.1,)</version>
                        <type>zip</type>
                    </assemblyArtifact>
                    <serverName>${project.artifactId}Server</serverName>
                    <include>${packaging.type}</include>
                </configuration>
            </plugin>
```

2.  Runt he move2kube command
`move2kube plan -s directory`

3. run the translate step
`move2kube translate m2k.plan`

4. The Dockerfile created is for JBoss:
```
FROM registry.access.redhat.com/ubi8/ubi:latest AS build_base
RUN yum install -y java-1.8.0-openjdk-devel
RUN yum install -y maven
COPY . /app
WORKDIR /app
RUN mvn package

# Run App
FROM registry.access.redhat.com/jboss-eap-6/eap64-openshift:latest
EXPOSE 8080
COPY --from=build_base /app/target/* /opt/eap/standalone/deployments/
```

**Expected behavior**
Either recognise that the image is for Liberty/OL and use Liberty/OL in the Dockerfile or ask which one should be chosen. 

**Desktop (please complete the following information):**
 - OS: Linux (Unbuntu 18.04), MacOS 11.x
 - Version (from homebrew)
``` 
move2kube version
v0.1.0
```

Regards, Brian

**Comment by ashokponkumar** [comment]
Thanks @bpaskin-ibm for logging the issue. We will evaluate it and get back. The pom.xml sample is good. But was wondering whether it would be possible to share sample working code?

**Comment by ashokponkumar** [comment]
In v3 we all the user which runtime to use.
