### ISSUE TITLE
Make shell script pass linter shellcheck.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#54]
# Description
This shell script is used to install the dependencies of the project.
Currently it does not pass checks by the linter `shellcheck` https://www.shellcheck.net/
https://github.com/konveyor/move2kube/blob/abea0c90ef78dc12fefd1d3cbf711b562170efa0/scripts/installdeps.sh#L22
```
Line 22:
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
          ^-- SC2003: expr is antiquated. Consider rewriting this using $((..)), ${} or [[ ]].
                      ^-- SC2046: Quote this to prevent word splitting.
```

# How to get started
❗ Please read the contribution guidelines first https://github.com/konveyor/move2kube/blob/master/contributing.md

As the error says rewrite the expression using one of `$((..)), ${} or [[ ]]`
Also make sure there are no other errors.
You can run shellcheck locally: https://github.com/koalaman/shellcheck
or as a vscode extension: https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck

# Guidelines
- Bash tutorial: https://mywiki.wooledge.org/BashGuide
- FAQ about common tasks: https://mywiki.wooledge.org/BashFAQ
- Things NOT to do: https://mywiki.wooledge.org/BashPitfalls
- Bash reference: https://mywiki.wooledge.org/BashSheet

**Comment by chrisgoutzi** [comment]
Hi @HarikrishnanBalagopal! I would love to try and fix that. Just to make sure, you want me to edit the file so that it passes the linter check?

**Comment by chrisgoutzi** [comment]
Sorry for the silly question, I somehow managed to miss the huge title

**Comment by HarikrishnanBalagopal** [comment]
@chrisgoutzi if you have done any work on this feel free to submit a PR.
Otherwise I would like to takeover.
