### ISSUE TITLE
Add support for Google's cloud native buildpack builders 

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#58]
Google recently announced support for cnb (https://cloud.google.com/blog/products/containers-kubernetes/google-cloud-now-supports-buildpacks/).

Move2kube can easily support it out of the box as part of its cnb containerisation support.

The change required would be to https://github.com/konveyor/move2kube/blob/3c4021771dcd4c986aa51ccc1c37546ecc7f1fee/internal/containerizer/cnbcontainerizer.go#L42

Add gcr.io/buildpacks/builder to the above array and then fix any tests that might need updates.

**Comment by ShajithaMohammed** [comment]
@ashokponkumar I would like to work on this.

**Comment by ashokponkumar** [comment]
> @ashokponkumar I would like to work on this.

sure. Reach out in the comments if you need more info.
