### ISSUE TITLE
Integration with application git repo to get code and commit changes

### ISSUE THREAD

**Issue by rmarting** [konveyor/move2kube#604]
**Is your feature request related to a problem? Please describe.**

Many applications are managed in Git repositories with all the source code needed, documentation and other artifacts needed to build, package and deploy the application. These git repositories are the source of truth of the application.

Now move2kube requires to have a local instance of that code or a zip (if you are using the UI) to analyze, traslate and transform the application. It could be a great feature that move2kube uses directly the git repository of the application to:

- checkout the code
- execute the actions locally, including the transformations
- Optionally push the changes into the original source code (in the same branch, in other, in a specific folder, ...)

After you use the application, not only have a transformed version to be deployed in your kubernetes cluster, also you have the new code updated to be used in the next iterations of the application. Otherwise you have to commit the resources manually. As developer I am getting the new resources automatically and integrated in my git repo to be used for the next steps of the migration process.

**Describe the solution you'd like**

Integrate automatically the new changes of the application into the original git repository to advance in the migration project. Avoid to have everything locally and avoid loss something.

**Describe alternatives you've considered**

**Additional context**

**Comment by Rahulkhinchi03** [comment]
Hi @rmarting @ashokponkumar ,
I have applied for the `CNCF - Konveyor: Move2Kube Allow customizations to be added as remote git repo path` as an LFX Mentee. 

Looking forward to hearing soon from the team and working with you all :-)

**Comment by avinabneogy23** [comment]
Heyy @ashokponkumar and @rmarting ,I have applied for this project ```CNCF Konveyor: Move2Kube Allow customizations to be added as remote git repo path``` as a mentee.I am really excited to work on this project and looking forward to hearing from you soon!

**Comment by c0d33ngr** [comment]
Hi @rmarting and @ashokponkumar, I just applied for the `CNCF Konveyor: Move2Kube Allow customizations to be added as remote git repo path` as a mentee. Looking forward to making meaningful contributions to this project.

**Comment by HarikrishnanBalagopal** [comment]
Maybe relevant https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content

**Comment by rmarting** [comment]
Sorry @Rahulkhinchi03, @avinabneogy23, and @c0d33ngr but I am not sure why you are tagging me about ... as I don't know anything about the topic you are speaking on.

**Comment by kmehant** [comment]
We have this feature implemented by @venkatbandarupalli, can we close this? @ashokponkumar 

https://github.com/konveyor/move2kube/pulls?q=is%3Apr+author%3Avenkatbandarupalli+remote+

**Comment by ashokponkumar** [comment]
> We have this feature implemented by @venkatbandarupalli, can we close this? @ashokponkumar
> 
> https://github.com/konveyor/move2kube/pulls?q=is%3Apr+author%3Avenkatbandarupalli+remote+

sure. Thanks @kmehant @venkatbandarupalli .
