### ISSUE TITLE
Declare an argument to choose the container runtime use (docker, podman)

### ISSUE THREAD

**Issue by rmarting** [konveyor/move2kube#618]
**Is your feature request related to a problem? Please describe.**

Each user could have different use cases, and different container runtime to use, so if the use could choose the container runtime could be a great feature. 

It could be an argument to request to the user, or a question in the UI to choose the container engine to use in the scripts and deployment artifacts generated by the tool. Then the user could choose the right container runtime for his/her environment.

The idea is similar when you choose the platform (k8s or OpenShift). Then the artifacts generated will be aligned with that decession.

Of course, `docker` could be the default one if the user does not set `podman`.

**Describe the solution you'd like**

Define a new argument in move2kube cli to choose which container engine use:

E.g:

```shell
$ move2kube --container-runtime podman
```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ashokponkumar** [comment]
Fixed by #700
