### ISSUE TITLE
Add support for AKS/EKS/GKE/etc based Kubernetes Clusters

### ISSUE THREAD

**Issue by johnrevans6** [konveyor/move2kube#674]
Currently there exists support for OCP, and K8s. Depending on the provider, K8s annotations can vary. For example, in GKE, we use the the annotation:

ingress.gcp.kubernetes.io/pre-shared-cert 

to provide a cert that gets applied on the ingress. This means that a user either needs to add these annotations in manually post-run, or the automation needs to provide additional functionality that supports these additions.

**Comment by HarikrishnanBalagopal** [comment]
> we use the the annotation:
> ingress.gcp.kubernetes.io/pre-shared-cert
> to provide a cert that gets applied on the ingress. 

@johnrevans6 is this still the case in K8s 1.16+ with `networking.k8s.io/v1/Ingress` ?
There is TLS support without annotations now https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

AKS/EKS/GKE cluster types can be selected as well.
https://github.com/konveyor/move2kube/tree/main/assets/built-in/transformers/kubernetes/clusterselector/clusters

Feel free to comment on this issue or create a new one if this is still relevant in the latest Move2Kube version `v0.3.x`
