### ISSUE TITLE
Running buildimages.sh within the scripts directory returns an error

### ISSUE THREAD

**Issue by jameslabocki** [konveyor/move2kube#690]
**Describe the bug**
Running ./buildimages.sh within the scripts directory produces an error.

**To Reproduce**
Run ./buildimages.sh in the scripts directory
[ec2-user@ip-172-30-0-222 scripts]$ ./buildimages.sh 
./buildimages.sh: line 18: ./scripts/builddockerimages.sh: No such file or directory
/home/ec2-user/myproject/scripts

**Expected behavior**
It should work or tell you how to run it correctly.

**Desktop (please complete the following information):**
$ move2kube version
v0.3.0-beta.3

**Comment by HarikrishnanBalagopal** [comment]
```
Expected behavior
It should work or tell you how to run it correctly.
```

1st approach
We could do something like detect the path where the script is located and have all paths relative to that directory.
https://stackoverflow.com/questions/24112727/relative-paths-based-on-file-location-instead-of-current-working-directory
```bash
#!/bin/bash
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

cd "$parent_path"
cat ../some.text
```

2nd approach
To give a warning we still need to detect the script path to decide whether to give a warning or not.
