### ISSUE TITLE
ERROR "The Input name is empty" is coming

### ISSUE THREAD

**Issue by Monu2022** [konveyor/move2kube#733]
**Describe the bug**
We created an m2kconfig.yaml and added private registry configuration and other configurations but when we run transform using -f option and give config yaml file, it gives  "The Input name is empty" error.Also it creates file with name -secret.yaml in deploy/yamls file which doesn't run using kubectl command as file name starts with hyphen.

**To Reproduce**
1. Create your own m2kconfig_test.yaml file and add private registry information
2. run transform with the above file

**Expected behavior**
Error should not come and secret file name should not start with hyphen

**Screenshots**
![image](https://user-images.githubusercontent.com/97747936/149545913-7defe7bc-148b-4220-a844-d588653f5c1a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version v0.3.0+unreleased. `move2kube version` should return it.

**Additional context**
NA

**Comment by ashokponkumar** [comment]
With v0.3.0 rc.2, this issue is fixed.
