### ISSUE TITLE
not able to access the frontend service : giving a blank page 

### ISSUE THREAD

**Issue by sakaul88** [konveyor/move2kube#819]
hi team , i am trying to deploy https://move2kube.konveyor.io/tutorials/migration-workflow on IBM openshift , my all pods UP but not able to access the frontend service . more details can be found over : 
https://kubernetes.slack.com/archives/CR85S82A2/p1656170502555979

**Comment by Akash-Nayak** [comment]
By using the latest version of Move2Kube for the migration and making quay repositories visibility public, the pods were running successfully on IBM Openshift and all the enterprise-app components were all working fine. Also, PR https://github.com/konveyor/move2kube/pull/834 updated the Node version selection logic.

So, closing this issue.
