### ISSUE TITLE
Any good example for external executale transformer

### ISSUE THREAD

**Issue by vivekskrishna** [konveyor/move2kube#852]
**Describe the bug**
The documentation does not have clear example on how to use external executable transformer type.

**To Reproduce**

**Expected behavior**
improved documentation with an example which shows how to create yaml config to use the external executable transformer will make it easy to use this feature.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. RHEL]
 - Version [e.g. 22]. `move2kube version` should return it.

**Additional context**

**Comment by ashokponkumar** [comment]
Thanks @vivekskrishna for the query. We are in the process of enhancing the interface of the external executable transformer and writing a tutorial. Will share it once it is ready.

In the meanwhile, just wondering whether a starlark based transformer will suffice the need. (https://move2kube.konveyor.io/tutorials/customizing-the-output/add-custom-files-directories-in-custom-locations). It can do most transformations. If you have a specific requirement in mind, let us know, and we can see if the built-in transformers or starlark based transformer can achieve the job, or if we need an external executable transformer for it.

**Comment by vivekskrishna** [comment]
Will check it out and revert. Thank you

**Comment by HarikrishnanBalagopal** [comment]
Closing this as completed https://move2kube.konveyor.io/transformers/external
