### ISSUE TITLE
Add support for multiple deployments in a single yaml file

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#86]
Identify an approach to support more than one deployment in a single yaml (https://github.com/konveyor/move2kube/blob/7caa5fd079ad6efe44ca3fb19806e8d024719689/internal/apiresourceset/k8sapiresourceset.go#L92) while loading Kubernetes resources.

**Comment by HarikrishnanBalagopal** [comment]
We can use an approach similar to https://github.com/konveyor/move2kube/blob/master/internal/common/tar.go#L84-L86
but for yaml instead of tar.
