### ISSUE TITLE
test: Test the container package.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#884]
> ⚠️  **Don't forget to read our contribution guidelines before you start working on an issue** https://github.com/konveyor/move2kube/blob/main/contributing.md

# Description

Since Move2Kube moved from v1 to v2 and then to the v3 architecture, the test coverage has dropped significantly.
One of the many places that need unit tests are the files in the `container` package.
It is a core part of Move2Kube's `transform` functionality and yet has only a few unit tests.

https://github.com/konveyor/move2kube/blob/6ee8f6be3e7f9b9eb0bb1200b468ac95018f244f/environment/container

This package deals with pulling container images, starting and stopping containers, etc. using different runtimes like Docker and Podman.
It can also copy files/directories from the local filesystem into the container and vice versa.

https://github.com/konveyor/move2kube/blob/6ee8f6be3e7f9b9eb0bb1200b468ac95018f244f/environment/container/utils.go

# How to get started

For this issue you should start with some simple tests that pulls a container image, starts a container, copies a file into the container, etc.
Next step would be to make slight changes to the files in the directory and create a separate subtest for each scenario.
Some scenarios that are good to test:
- Detecting if a container runtime is installed and which one (Docker/Podman).
- Pulling a container image.
- Starting a container using the image.
- Copying a normal file into a container.
- Copying a normal directory into a container.
- Copying a normal directory from the container to the local filesystem.
- Copy function called on an empty directory.
- Directory we don't have permission to read.
- Directory with several subdirectories

# How to add unit tests

Some guidelines:
- Look at the other tests in the package/project and write similar tests. Example:
  https://github.com/konveyor/move2kube/blob/6ee8f6be3e7f9b9eb0bb1200b468ac95018f244f/environment/container/dockerengine_test.go#L25-L61
  https://github.com/konveyor/move2kube/blob/6ee8f6be3e7f9b9eb0bb1200b468ac95018f244f/types/collection/cluster_test.go#L28-L105
- Use subtests to test different paths through the function.
- Don't worry about testing every single path through the function. Focus on common use cases and failure modes.

Some helpful resources on how to write unit tests in Go:
- https://blog.golang.org/subtests
- https://youtu.be/hVFEV-ieeew

# Code to be tested

https://github.com/konveyor/move2kube/blob/6ee8f6be3e7f9b9eb0bb1200b468ac95018f244f/environment/container

**Comment by moki1202** [comment]
@HarikrishnanBalagopal I've written a few (rather simple) go tests so I think I can give this a go :)

**Comment by punithnayak** [comment]
Hey @HarikrishnanBalagopal Can you assign me so that  can raise a Pr

**Comment by HarikrishnanBalagopal** [comment]
> Hey @HarikrishnanBalagopal Can you assign me so that can raise a Pr

Thanks for your interest. I have assigned the issue to you. Feel free to ask in the #konveyor Slack channel to get help https://kubernetes.slack.com/archives/CR85S82A2

**Comment by akagami-harsh** [comment]
hey @HarikrishnanBalagopal, what's the status on the issue

**Comment by HarikrishnanBalagopal** [comment]
@akagami-harsh Fixed in https://github.com/konveyor/move2kube/pull/994 and subsequent PRs
