### ISSUE TITLE
bug: Failed to parameterize error while running move2kube transform on docker-compose file 

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#958]
**Describe the bug**
I am getting an error `failed to parameterize YAML files in the source directory` while running move2kube transform on the below docker-compose file 

**To Reproduce**
1. Input `docker-compose.yml`

```console
services:
  hello_worldDLR_BR_OP_TAG_BR_CL:
    command:
    - /bin/echo
    - Hello world
    deploy:
      placement:
        constraints:
        - node.a.b.c == true
    environment:
    - env:${CODE}
    image: ubuntu:${TAG}
    links:
    - redis${TAG}:redis${TAG}
    ports:
    - ${UIPORT}:8443
version: "3"
```

2. Run `move2kube transform` over the source folder [dc-input.zip](https://github.com/konveyor/move2kube/files/10672422/dc-input.zip) which contains the above docker-compose file.

3. Choose the cluster type as `IBM Openshift` or `Openshift`. (The error doesn't appear if I select `Kubernetes` as the cluster type.)

```console
? Choose the cluster type:
ID: move2kube.target."default".clustertype
Hints:
- Choose the cluster type you would like to target

  [Use arrows to move, type to filter]
  AWS-EKS
  Azure-AKS
  GCP-GKE
  IBM-IKS
> IBM-Openshift
  Kubernetes
  Openshift
```

4. It throws an error towards end of transformation.

```console
? Provide the ingress host domain
ID: move2kube.target."default".ingress.host
Hints:
- Ingress host domain is part of service URL

 t14.com
INFO[0041] Transformer Kubernetes Done                  
INFO[0041] Transformer ClusterSelector processing 2 artifacts 
INFO[0041] Transformer ClusterSelector Done             
INFO[0041] Transformer Tekton processing 2 artifacts    
INFO[0041] Transformer Tekton Done                      
INFO[0041] Created 30 pathMappings and 10 artifacts. Total Path Mappings : 30. Total Artifacts : 3. 
INFO[0041] Iteration 4 - 10 artifacts to process        
INFO[0041] Transformer Parameterizer processing 6 artifacts 
WARN[0041] Error in walking through files due to : "stat /var/folders/sw/_kjrz98j3ws1qj7zz6chzhrr0000gn/T/move2kube1729845829/environment-Parameterizer-3160189886/2622198968/deploy/cicd/buildconfig: no such file or directory" 
ERRO[0041] failed to parameterize the YAML files in the source directory /var/folders/sw/_kjrz98j3ws1qj7zz6chzhrr0000gn/T/move2kube1729845829/environment-Parameterizer-3160189886/2622198968/deploy/cicd/buildconfig and write to output directory /var/folders/sw/_kjrz98j3ws1qj7zz6chzhrr0000gn/T/move2kube1729845829/environment-Parameterizer-3160189886/2995956675/buildconfig-parameterized . Error: "stat /var/folders/sw/_kjrz98j3ws1qj7zz6chzhrr0000gn/T/move2kube1729845829/environment-Parameterizer-3160189886/2622198968/deploy/cicd/buildconfig: no such file or directory"
```
 
**Expected behavior**
The above error should not show up while running `move2kube transform`

**Screenshots**

<img width="1786" alt="Screenshot 2023-02-07 at 12 33 01 PM" src="https://user-images.githubusercontent.com/14867323/217171615-c5bad9d3-6dea-49e3-bcc2-79b445a4cee9.png">

**Desktop (please complete the following information):**
```console
move2kube version -l                  
version: v0.3.0+unreleased
gitCommit: 0d8f71ad8264029e04b5d919ca7f5ccb9c1d8c7d
gitTreeState: clean
goVersion: go1.18.1
platform: darwin/amd64
```

**Comment by HarikrishnanBalagopal** [comment]
Seems the `ir.ContainerImages` is empty

**Comment by Akash-Nayak** [comment]
I just checked that the same issue can also be reproduced with the move2kube-demos docker-compose sample https://github.com/konveyor/move2kube-demos/blob/main/samples/docker-compose/multiple-services/docker-compose.yaml if I comment-out/remove lines [6](https://github.com/konveyor/move2kube-demos/blob/e42a1ea4235ae5e9f3389b2bc57098759dd02ca4/samples/docker-compose/multiple-services/docker-compose.yaml#L6) and [17](https://github.com/konveyor/move2kube-demos/blob/e42a1ea4235ae5e9f3389b2bc57098759dd02ca4/samples/docker-compose/multiple-services/docker-compose.yaml#L17), i.e., if the docker-compose file doesn’t have the `build` key for any service.

**Comment by HarikrishnanBalagopal** [comment]
Tried adding the `build` key to the Dockerfile in the original post:
```
services:
  hello_worldDLR_BR_OP_TAG_BR_CL:
    build: .
    command:
    - /bin/echo
    - Hello world
    deploy:
      placement:
        constraints:
        - node.a.b.c == true
    environment:
    - env:${CODE}
    image: ubuntu:${TAG}
    links:
    - redis${TAG}:redis${TAG}
    ports:
    - ${UIPORT}:8443
version: "3"
```
This works without error, produces `ContainerImages` and `BuildConfig`

**Comment by HarikrishnanBalagopal** [comment]
fixed by adding a check before creating the artifact in BuildConfig transformer https://github.com/konveyor/move2kube/pull/963/files#diff-2a1ff621d16165f6fe85b3c4599804d42481d872fbebab5c38136dce75c83e01R152
