### ISSUE TITLE
An alternative platform to Katacoda

### ISSUE THREAD

**Issue by lakshay-nasa** [konveyor/move2kube#964]
**Describe the bug**
Since the Move2Kube [website](https://move2kube.konveyor.io/) currently mentions [Katacoda](https://katacoda.com/move2kube) as the platform for showcasing the functionalities of Move2Kube to its users, it would be beneficial to find an alternative as Katacoda has been outdated since June 22nd, 2022. This will ensure users have an up-to-date and reliable platform for experiencing Move2Kube's capabilities.

**Solution**
To ensure that there is a demo available for each of the tutorials on konveyor.io, it is advised to create a corresponding demo on the platform like https://killercoda.com/

**Comment by HarikrishnanBalagopal** [comment]
Now we have a WASM version that people can try out in their browsers https://move2kube.konveyor.io/experimental
