### ISSUE TITLE
Add support for StatefulSet and Headless service

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#971]

**Comment by KrishAryan** [comment]
@Akash-Nayak sir, can you please add the description to this issue?

**Comment by Akash-Nayak** [comment]
Hello @KrishAryan, this feature has already been added to Move2Kube through https://github.com/konveyor/move2kube/pull/1088. So, I am closing this issue. I would encourage you to look at other open issues, and also please feel free to try out Move2Kube https://move2kube.konveyor.io/tutorials.
