### ISSUE TITLE
bug: containerized transformer checks fails on s390x machine

### ISSUE THREAD

**Issue by kmehant** [konveyor/move2kube#995]
**Describe the bug**
Check step of pulling and running https://quay.io/repository/konveyor/hello-world image is failing as the image is not supported for s90x platform

**Expected behavior**
https://quay.io/repository/konveyor/hello-world image for s390x should be available on quay

**Comment by HarikrishnanBalagopal** [comment]
@kmehant can we close this? you pushed the hello-world image right?
